### ISSUE TITLE
rstudio-2024.04.2.764 fails to compile with boost-1.85.0

### ISSUE THREAD

**Issue by fvalenduc** [jgenco/jgenco-overlay#26]
rstudio needed to be rebuild after upgrading boost to 1.85.0. However, it fails with this error:

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/tmp/portage/sci-mathematics/rstudio-2024.04.2.764/work/rstudio-2024.04.2-764/src/node/desktop/node_modules/node-system-fonts/build'
  CXX(target) Release/obj.target/system-fonts/src/lib/FontManager.o
In file included from ../src/lib/FontManager.cc:5:
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, imp::Sig)’:
../../nan/nan.h:2548:19: error: no matching function for call to ‘v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&)’
 2548 |   tpl->SetAccessor(
      |   ~~~~~~~~~~~~~~~~^
 2549 |       name
      |       ~~~~         
 2550 |     , getter_
      |     ~~~~~~~~~      
 2551 |     , setter_
      |     ~~~~~~~~~      
 2552 |     , obj
      |     ~~~~~          
 2553 |     , settings
      |     ~~~~~~~~~~     
 2554 |     , attribute
      |     ~~~~~~~~~~~    
 2555 | #if (NODE_MODULE_VERSION < NODE_16_0_MODULE_VERSION)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2556 |     , signature
      |     ~~~~~~~~~~~    
 2557 | #endif
      | ~~~~~~             
 2558 |   );
      |   ~                
In file included from /var/tmp/portage/sci-mathematics/rstudio-2024.04.2.764/work/.cache/node-gyp/22.3.0/include/node/v8-function.h:15,
                 from /var/tmp/portage/sci-mathematics/rstudio-2024.04.2.764/work/.cache/node-gyp/22.3.0/include/node/v8.h:33,
                 from /var/tmp/portage/sci-mathematics/rstudio-2024.04.2.764/work/.cache/node-gyp/22.3.0/include/node/node.h:73,
                 from ../src/lib/FontManager.cc:2:
/var/tmp/portage/sci-mathematics/rstudio-2024.04.2.764/work/.cache/node-gyp/22.3.0/include/node/v8-template.h:1049:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
 1049 |   void SetAccessor(

**Comment by jgenco** [comment]
This is a `nodejs` version problem.  I fixed a `Boost-1.85.0` problem with commit 23c53a3a737b38638411a4f0acd34c581388a730.  For the time being you can try using `rstudio-2024.07.0.267` which uses a newer Electron version.

For reference I'm using `nodejs-22.3.0` and I'm seeing the same thing.

**Comment by jgenco** [comment]
I couldn't get it to build Electron with `nodejs-22` so I have changed the requirements to `<nodejs-21` for electron version.
